### ISSUE TITLE
Responder trait derivation for actix-web

### ISSUE THREAD

**Issue by ZizhengTai** [djc/askama#204]
I'm experimenting with askama and actix-web, and noticed the `Responder` trait derivation sometimes doesn't work. Here is an example project:

Cargo.toml:
```toml
[package]
name = "try-askama"
version = "0.1.0"
authors = ["Z"]
edition = "2018"

[dependencies]
actix-web = "0.7"
askama = { version = "0.7", features = ["with-actix-web"] }
```

src/main.rs:
```rust
use actix_web::{App, HttpRequest};
use askama::Template;

#[derive(Template)]
#[template(ext = "html", source = "Hello, {{ name }}!")]
struct HelloTemplate {
    name: &'static str,
}

fn index(_: &HttpRequest) -> HelloTemplate {  // <-- Compiles
// fn index(_: &HttpRequest) -> impl Template { // <-- DOESN'T compile
    HelloTemplate { name: "John" }
}

fn main() {
    App::new().resource("/", |r| r.get().f(index));
}
```

If I try to make the handler return `impl Template` (or anything like `Result<impl Template>`, `Box<Future<impl Template, Error>>`, etc.), I get this error:

```
error[E0277]: the trait bound `impl askama::Template: actix_web::handler::Responder` is not satisfied
  --> src/main.rs:15:42
   |
15 |     App::new().resource("/", |r| r.get().f(index));
   |                                          ^ the trait `actix_web::handler::Responder` is not implemented for `impl askama::Template`
```
