### ISSUE TITLE
Use with the latest version of Iron

### ISSUE THREAD

**Issue by hajifkd** [djc/askama#63]
The required version of Iron with "with-iron" feature is fixed to 0.5, so that if we try to use the latest version of Iron (0.6), the build fails.
I am not sure whether this is appropriate, but it would be sufficient to relax the version specification;

```toml
[dependencies]
...
iron = { version = ">= 0.5", optional = true }
...
```

(I have checked that this works: dbea8955b7e8ccae35abeb4178d74ba0f038be04)

In terms of the compatibility,  just like [iron/staticfile](https://github.com/iron/staticfile/blob/master/Cargo.toml), 

```toml
iron = { version = ">= 0.5, < 0.7", optional = true }
```

might be better.
