### ISSUE TITLE
could not compile `askama_shared`

### ISSUE THREAD

**Issue by wormtql** [djc/askama#642]
I'm building wasm in netlify, when I run `wasm-pack build` I get this error.
But when I run `wasm-pack` in my local windows machine I didn't get any error.

rust channel: nightly-2022-01-14
rustc: 1.60.0-nightly

my Cargo.toml:
```toml
[package]
name = "mona"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[profile.release]
lto = true
opt-level = 3

[dependencies]
mona_derive = { path = "../mona_derive" }
wasm-bindgen = { version = "0.2.63", features = ["serde-serialize"] }
lazy_static = "1.4.0"
rand = "0.8.4"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.78"
console_error_panic_hook = { version = "0.1.7", optional = true }
web-sys = { version = "0.3.55", features = ["console"] }
getrandom = { version = "0.2", features = ["js"] }
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
smallvec = "1.8.0"
askama = "0.11"
askama_escape = "0.10.2"
strum = "0.23"
strum_macros = "0.23"

```

output from netlify:
```
6:06:17 PM:    Compiling toml v0.5.8
6:06:17 PM:    Compiling num v0.4.0
6:06:17 PM:    Compiling askama_shared v0.12.0
6:06:17 PM:    Compiling js-sys v0.3.55
6:06:17 PM:    Compiling console_error_panic_hook v0.1.7
6:06:17 PM:    Compiling askama v0.11.0
6:06:17 PM:    Compiling getrandom v0.2.4
6:06:17 PM:    Compiling web-sys v0.3.55
6:06:17 PM:    Compiling rand_core v0.6.3
6:06:17 PM:    Compiling rand_chacha v0.3.1
6:06:17 PM:    Compiling rand v0.8.4
6:06:17 PM: error: could not compile `askama_shared`
6:06:17 PM: Caused by:
6:06:17 PM:   process didn't exit successfully: `rustc --crate-name askama_shared --edition=2018 /opt/buildhome/.cargo/registry/src/github.com-1ecc6299db9ec823/askama_shared-0.12.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="config"' --cfg 'feature="humansize"' --cfg 'feature="num-traits"' --cfg 'feature="percent-encoding"' --cfg 'feature="serde"' --cfg 'feature="toml"' -C metadata=405a1ad42a2b0b57 -C extra-filename=-405a1ad42a2b0b57 --out-dir /opt/build/repo/mona/target/wasm32-unknown-unknown/release/deps --target wasm32-unknown-unknown -L dependency=/opt/build/repo/mona/target/wasm32-unknown-unknown/release/deps -L dependency=/opt/build/repo/mona/target/release/deps --extern askama_escape=/opt/build/repo/mona/target/wasm32-unknown-unknown/release/deps/libaskama_escape-52d5c844f8869eee.rmeta --extern humansize=/opt/build/repo/mona/target/wasm32-unknown-unknown/release/deps/libhumansize-61fd1e80587e5713.rmeta --extern nom=/opt/build/repo/mona/target/wasm32-unknown-unknown/release/deps/libnom-4e2fa0882c440dec.rmeta --extern num_traits=/opt/build/repo/mona/target/wasm32-unknown-unknown/release/deps/libnum_traits-107c76eccbdf7552.rmeta --extern percent_encoding=/opt/build/repo/mona/target/wasm32-unknown-unknown/release/deps/libpercent_encoding-1650dda5d8c68d2f.rmeta --extern proc_macro2=/opt/build/repo/mona/target/wasm32-unknown-unknown/release/deps/libproc_macro2-1d8be359cceb60c4.rmeta --extern quote=/opt/build/repo/mona/target/wasm32-unknown-unknown/release/deps/libquote-0ffbc2387a95f660.rmeta --extern serde=/opt/build/repo/mona/target/wasm32-unknown-unknown/release/deps/libserde-5ebd470a016f03dd.rmeta --extern syn=/opt/build/repo/mona/target/wasm32-unknown-unknown/release/deps/libsyn-1898e27620d74d9c.rmeta --extern toml=/opt/build/repo/mona/target/wasm32-unknown-unknown/release/deps/libtoml-4f6a9006ce7e0577.rmeta --cap-lints allow` (signal: 9, SIGKILL: kill)
Error: Compiling your crate to WebAssembly failed
```
