### ISSUE TITLE
Markdown filter requires markdown feature error, even though the feature is enabled

### ISSUE THREAD

**Issue by Asha20** [djc/askama#656]
Hey, I'm not sure if I'm doing something wrong here or it's a bug, but I can't seem to get the `markdown` filter working, even though the relevant feature is enabled; I keep getting a proc macro compile error. Any help would be greatly appreciated!

My code looks something like this:

> `src/main.rs`

```rust
use askama::Template;

#[derive(Template)]
#[template(path = "basic.jinja")]
struct BasicTemplate {
    content: String,
}

fn main() {}
```

> `templates/basic.jinja`

```hbs
{{ content|markdown }}
```

> `Cargo.toml`

```toml
[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = { version = "0.11.1", features = ["markdown"] }
```

**Comment by Kijewski** [comment]
Huh, I can reproduce the error, but I can't see the reason. Even if I explicitly depend on askama_shared/markdown it does not work.

```toml
[dependencies.askama_shared]
features = ["markdown"]
```
I don't see a typo or anything, and hd does not show any stray zero-width characters. @djc, do you have an idea?
