### ISSUE TITLE
Unable to use with askama_axum: conflict with return type of IntoResponse error

### ISSUE THREAD

**Issue by sigaloid** [djc/askama#692]
```rust
askama_axum::IntoResponse::into_response(Message {})
```

Message is a valid askama template.

Error: 
```
mismatched types
expected struct `Response<http_body::combinators::box_body::UnsyncBoxBody<_, axum::Error>>`
   found struct `Response<http_body::combinators::box_body::UnsyncBoxBody<_, axum_core::error::Error>>`
perhaps two different versions of crate `axum_core` are being used? rustcE0308
```
![image](https://user-images.githubusercontent.com/69441971/173164768-bb1c33b3-c514-464b-a059-9a75f1594f3f.png)

Relevant Cargo.toml:
```toml
askama = { version = "0.11.1" }
askama_axum = "0.1.0"
axum = { version = "0.5.7", features = ["http2", "tower-log"] }
```

As seen[ here, ](https://docs.rs/askama_axum/latest/askama_axum/trait.IntoResponse.html) into_response returns an error of `axum_core::error::Error` but axum seems to expect `axum::Error`. 

My code right now returns a Response, one of which is a redirect, the other of which is an askama template. To avoid any problems with using the same-named trait IntoResponse from two different crates (`axum::response::IntoResponse` and `askama_axum::IntoResponse`) I used the fully qualified path.  

![image](https://user-images.githubusercontent.com/69441971/173164933-e52d04b4-d937-4266-bc1f-a1b8b83b4912.png)

**Comment by Kijewski** [comment]
The version on crates.io is still synchronous to axum 0.4. The changes in #657 were not published, yet. Please try if the current git head works for you.

**Comment by sigaloid** [comment]
Ah, I tried using the git head for askama but not askama_axum. Thanks, that fixes it :) I'll close as it's not dependent on that PR but rather crates.io publication.

**Comment by logankeenan** [comment]
For anyone else who runs across this issue, see example solution below:

```toml
askama = { git = "https://github.com/djc/askama.git", rev="c441459a27eb7c0c476ce70833e05224ba6894fd"}
askama_axum = { git = "https://github.com/djc/askama.git", package="askama_axum", rev="c441459a27eb7c0c476ce70833e05224ba6894fd"}
```
