### ISSUE TITLE
Whitespace config not working?

### ISSUE THREAD

**Issue by alakhpc** [djc/askama#749]
Hi, I can't seem to get the `whitespace` option to work.

This is the file I'm trying to format
```j2
docker run -d \
    {% for volume in volumes %}
    -v {{ volume }} \
    {% endfor %}
    -e VERSION=docker \
    --restart unless-stopped \
    redis
```

askama.toml
```toml
[general]
dirs = ["scripts"]
whitespace = "suppress"
```

I've tried `suppress` and `minimize`, but both give this
```j2
docker run -d \
    
    -v /v1:/v1 \
    
    -v /v2:/v2 \
    
    -e VERSION=docker \
    --restart unless-stopped \
    redis
```
