### ISSUE TITLE
Can't get custom syntax to work

### ISSUE THREAD

**Issue by Zwo1in** [djc/askama#774]
Hi, probably I'm missing something obvious, but I can't get my custom syntax working.

This is my `akama.toml`:

```toml
[[syntax]]
name = "tex"
block_start = "<<"
block_end = ">>"
comment_start = "<#"
comment_end = "#>"
expr_start = "<@"
expr_end = "@>"

```

And this code doesn't work:

```rust
#[derive(Template)]
#[template(source = "<< invoice_num >>", syntax = "tex", ext = "txt")]
struct MainTex<'a> {
    invoice_num: &'a str,
}
```

```
error: unable to parse template:
       
       "<< invoice_num >>"
  --> src/main.rs:81:10
   |
81 | #[derive(Template)]
   |          ^^^^^^^^
   |
   = note: this error originates in the derive macro `Template` (in Nightly builds, run with -Z macro-backtrace for more info)
```

I've tried a few completely different setups, even the ones from the book, but none of it worked.

With default syntax it's completely ok.

```rust
#[derive(Template)]
#[template(source = "{{ invoice_num }}", ext = "txt")]
struct MainTex<'a> {
    invoice_num: &'a str,
}
```

I was looking for examples of custom syntax in `testing` but without a success.
